---
http_interactions:
- request:
    method: head
    uri: http://localhost:9200/kelasi_test_users
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Content-Type:
      - text/plain; charset=UTF-8
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 15 Nov 2013 12:23:52 GMT
- request:
    method: post
    uri: http://localhost:9200/kelasi_test_users
    body:
      encoding: UTF-8
      string: '{"mappings":{"user":{"properties":{"id":{"index":"not_analyzed","type":"string"},"first_name":{"type":"string"},"last_name":{"type":"string"},"universities":{"as":{},"type":"string"},"current_universities":{"as":{},"type":"string"}}}},"settings":{}}'
    headers:
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
      Content-Length:
      - '249'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Content-Length:
      - '31'
    body:
      encoding: UTF-8
      string: '{"ok":true,"acknowledged":true}'
    http_version: 
  recorded_at: Fri, 15 Nov 2013 12:23:52 GMT
- request:
    method: get
    uri: http://localhost:9200/_cluster/health?wait_for_status=yellow
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Content-Length:
      - '232'
    body:
      encoding: UTF-8
      string: '{"cluster_name":"elasticsearch_msk","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":40,"active_shards":40,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":40}'
    http_version: 
  recorded_at: Fri, 15 Nov 2013 12:23:53 GMT
recorded_with: VCR 2.7.0
